// 
#LIBDEFINE MAX_TEXREPLACE_GLOBAL_LIMIT 300
Int MAX_TEXREPLACE_GLOBAL = 0;
Str Encore_TexRelpace[MAX_TEXREPLACE_GLOBAL_LIMIT][3]; //tex texreplace defined
function int defineTextureReplace(str texture, str textureReplace)
{
    SetCVarString("_encore_temp_texture", texture);
    SetCVarString("_encore_temp_textureReplace", textureReplace);
    return ACS_NamedExecuteWithResult("encore_defineTexReplace_s");
}